[package]
name = "galaxyx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
paste = "1.0.6"
num-traits = "0.2.14"

[dependencies.sdl2]
version = "0.35.2"
features = ["bundled"]

